[package]
name = "my-counter"
version = "0.0.0"

[addresses]
StarcoinFramework = "0x1"
MyCounterAddr = "0x5e946f0d254240346f19e518d78d5390"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="cf1deda180af40a8b3e26c0c7b548c4c290cd7e7"}
